create table if not exists public.ad_payment_requests (
  id text primary key,
  store_id text not null,
  store_name text not null,
  plan_scope text not null,
  governorate_id text,
  district_id text,
  category_id text,
  headline text not null,
  description text,
  image_url text,
  phone text,
  whatsapp text,
  offer_badge text,
  duration_days integer not null,
  amount numeric not null,
  payment_method text not null check (payment_method in ('zaincash','mastercard')),
  recipient_account text not null,
  transfer_reference text,
  receipt_data text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  admin_notes text,
  created_at timestamptz default now(),
  reviewed_at timestamptz,
  expires_at timestamptz,
  text_color text default '#ffffff',
  background_color text default '#0f172a',
  font_family text default 'inherit',
  media_type text default 'image',
  media_items jsonb default '[]'::jsonb,
  design jsonb default '{}'::jsonb
);

alter table public.ad_payment_requests enable row level security;
